apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: website-kustomization
  namespace: website
spec:
  interval: 1m
  targetNamespace: website
  sourceRef:
    kind: GitRepository
    name: website-gitgepository
  path: flux
  prune: true
  timeout: 1m