# Puerto de nginx
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31234
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 30000
    hostPort: 8080
    listenAddress: "0.0.0.0"