apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth-kustomization
  namespace: auth
spec:
  interval: 1m
  targetNamespace: auth
  sourceRef:
    kind: GitRepository
    name: auth-gitrepository
  path: flux
  prune: true
  timeout: 1m