apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: api-kustomization
  namespace: api
spec:
  interval: 1m
  targetNamespace: api
  sourceRef:
    kind: GitRepository
    name: api-gitrepository
  path: flux
  prune: true
  timeout: 1m